server:
  port: 8080
  servlet:    context-path: /bootcamp
    
spring:  datasource:    driver-class-name: org.postgresql.Driver
    url: postgres://jageoundjxqqyj:f669f77a4c4a5822fd64006066c9dbc54b19fea8058607b51d8f0e9987f28f75@ec2-34-232-191-133.compute-1.amazonaws.com:5432/d1vnvl026k4usq
    username: jageoundjxqqyj
    password: f669f77a4c4a5822fd64006066c9dbc54b19fea8058607b51d8f0e9987f28f75  jpa:    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
    generate-ddl: true
    hibernate:      ddl-auto: none
      
application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend.
     
  
  
      
      
 
    